/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extonextgroup.extonext_v2;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DonationFilteredsearchCorp extends javax.swing.JFrame {

    /**
     * Creates new form DonationFilteredsearchCorp
     */
    public DonationFilteredsearchCorp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        profilemenu = new javax.swing.JMenuItem();
        logoutmenu = new javax.swing.JMenuItem();
        donationlistlistcorpbackground1 = new netbeanscomponents.Donationlistlistcorpbackground();
        logobutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        messagebutton = new javax.swing.JButton();
        profilebutton = new javax.swing.JButton();
        wishlistlist = new javax.swing.JPanel();
        item1 = new javax.swing.JPanel();
        itemcategory = new javax.swing.JLabel();
        Recieversmessage = new javax.swing.JLabel();
        recieveraddress = new javax.swing.JLabel();
        item2 = new javax.swing.JPanel();
        itemcategory1 = new javax.swing.JLabel();
        Recieversmessage1 = new javax.swing.JLabel();
        recieveraddress1 = new javax.swing.JLabel();
        item3 = new javax.swing.JPanel();
        itemcategory2 = new javax.swing.JLabel();
        Recieversmessage2 = new javax.swing.JLabel();
        recieveraddress2 = new javax.swing.JLabel();
        item4 = new javax.swing.JPanel();
        itemcategory3 = new javax.swing.JLabel();
        Recieversmessage3 = new javax.swing.JLabel();
        recieveraddress3 = new javax.swing.JLabel();

        jPopupMenu1.setBackground(new java.awt.Color(204, 0, 255));
        jPopupMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jPopupMenu1.setAlignmentX(10.0F);

        profilemenu.setBackground(new java.awt.Color(204, 0, 255));
        profilemenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        profilemenu.setForeground(new java.awt.Color(255, 255, 255));
        profilemenu.setText("Go Profile");
        profilemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilemenuMouseClicked(evt);
            }
        });
        profilemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilemenuActionPerformed(evt);
            }
        });
        jPopupMenu1.add(profilemenu);

        logoutmenu.setBackground(new java.awt.Color(204, 0, 255));
        logoutmenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        logoutmenu.setForeground(new java.awt.Color(255, 255, 255));
        logoutmenu.setText("Logout");
        logoutmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutmenuActionPerformed(evt);
            }
        });
        jPopupMenu1.add(logoutmenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logobutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/logo.png"))); // NOI18N
        logobutton.setBorder(null);

        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/backbutton.png"))); // NOI18N
        backbutton.setBorder(null);
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        messagebutton.setBackground(new java.awt.Color(255, 255, 255));
        messagebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/55x37messagebutton.png"))); // NOI18N
        messagebutton.setBorder(null);

        profilebutton.setBackground(new java.awt.Color(255, 255, 255));
        profilebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extonextgroup/extonext_v2/images/37x37profilebutton.png"))); // NOI18N
        profilebutton.setBorder(null);
        profilebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebuttonActionPerformed(evt);
            }
        });

        wishlistlist.setOpaque(false);
        wishlistlist.setLayout(new java.awt.GridLayout(4, 1));

        item1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        item1.setOpaque(false);

        itemcategory.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        itemcategory.setForeground(new java.awt.Color(0, 0, 0));
        itemcategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemcategory.setText("Need x");

        Recieversmessage.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Recieversmessage.setForeground(new java.awt.Color(0, 0, 0));
        Recieversmessage.setText("jLabel2");
        Recieversmessage.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        recieveraddress.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        recieveraddress.setForeground(new java.awt.Color(0, 0, 0));
        recieveraddress.setText("jLabel3");
        recieveraddress.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout item1Layout = new javax.swing.GroupLayout(item1);
        item1.setLayout(item1Layout);
        item1Layout.setHorizontalGroup(
            item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item1Layout.createSequentialGroup()
                .addComponent(itemcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(Recieversmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(recieveraddress, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        item1Layout.setVerticalGroup(
            item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(item1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recieveraddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recieversmessage, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
        );

        wishlistlist.add(item1);

        item2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        item2.setOpaque(false);

        itemcategory1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        itemcategory1.setForeground(new java.awt.Color(0, 0, 0));
        itemcategory1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemcategory1.setText("Need x");

        Recieversmessage1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Recieversmessage1.setForeground(new java.awt.Color(0, 0, 0));
        Recieversmessage1.setText("jLabel2");
        Recieversmessage1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        recieveraddress1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        recieveraddress1.setForeground(new java.awt.Color(0, 0, 0));
        recieveraddress1.setText("jLabel3");
        recieveraddress1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout item2Layout = new javax.swing.GroupLayout(item2);
        item2.setLayout(item2Layout);
        item2Layout.setHorizontalGroup(
            item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item2Layout.createSequentialGroup()
                .addComponent(itemcategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(Recieversmessage1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(recieveraddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        item2Layout.setVerticalGroup(
            item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemcategory1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(item2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recieveraddress1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recieversmessage1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
        );

        wishlistlist.add(item2);

        item3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        item3.setOpaque(false);

        itemcategory2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        itemcategory2.setForeground(new java.awt.Color(0, 0, 0));
        itemcategory2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemcategory2.setText("Need x");

        Recieversmessage2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Recieversmessage2.setForeground(new java.awt.Color(0, 0, 0));
        Recieversmessage2.setText("jLabel2");
        Recieversmessage2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        recieveraddress2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        recieveraddress2.setForeground(new java.awt.Color(0, 0, 0));
        recieveraddress2.setText("jLabel3");
        recieveraddress2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout item3Layout = new javax.swing.GroupLayout(item3);
        item3.setLayout(item3Layout);
        item3Layout.setHorizontalGroup(
            item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item3Layout.createSequentialGroup()
                .addComponent(itemcategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(Recieversmessage2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(recieveraddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        item3Layout.setVerticalGroup(
            item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemcategory2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(item3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recieveraddress2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recieversmessage2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
        );

        wishlistlist.add(item3);

        item4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        item4.setOpaque(false);

        itemcategory3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        itemcategory3.setForeground(new java.awt.Color(0, 0, 0));
        itemcategory3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemcategory3.setText("Need x");

        Recieversmessage3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Recieversmessage3.setForeground(new java.awt.Color(0, 0, 0));
        Recieversmessage3.setText("jLabel2");
        Recieversmessage3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        recieveraddress3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        recieveraddress3.setForeground(new java.awt.Color(0, 0, 0));
        recieveraddress3.setText("jLabel3");
        recieveraddress3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout item4Layout = new javax.swing.GroupLayout(item4);
        item4.setLayout(item4Layout);
        item4Layout.setHorizontalGroup(
            item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(item4Layout.createSequentialGroup()
                .addComponent(itemcategory3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(Recieversmessage3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(recieveraddress3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        item4Layout.setVerticalGroup(
            item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemcategory3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(item4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recieveraddress3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Recieversmessage3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
        );

        wishlistlist.add(item4);

        javax.swing.GroupLayout donationlistlistcorpbackground1Layout = new javax.swing.GroupLayout(donationlistlistcorpbackground1);
        donationlistlistcorpbackground1.setLayout(donationlistlistcorpbackground1Layout);
        donationlistlistcorpbackground1Layout.setHorizontalGroup(
            donationlistlistcorpbackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donationlistlistcorpbackground1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(logobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 594, Short.MAX_VALUE)
                .addComponent(messagebutton)
                .addGap(0, 0, 0)
                .addComponent(profilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donationlistlistcorpbackground1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(wishlistlist, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        donationlistlistcorpbackground1Layout.setVerticalGroup(
            donationlistlistcorpbackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donationlistlistcorpbackground1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(donationlistlistcorpbackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(donationlistlistcorpbackground1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(messagebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profilebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logobutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(wishlistlist, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(donationlistlistcorpbackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(donationlistlistcorpbackground1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backbuttonActionPerformed

    private void profilebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebuttonActionPerformed
        // TODO add your handling code here:
        jPopupMenu1.show(this,989,117);
    }//GEN-LAST:event_profilebuttonActionPerformed

    private void profilemenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilemenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profilemenuMouseClicked

    private void profilemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilemenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profilemenuActionPerformed

    private void logoutmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutmenuActionPerformed
        // TODO add your handling code here:
        infoBox("Successfully logged out" , "logout" );
    }//GEN-LAST:event_logoutmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonationFilteredsearchCorp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonationFilteredsearchCorp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonationFilteredsearchCorp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonationFilteredsearchCorp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonationFilteredsearchCorp().setVisible(true);
            }
        });
    }
    
     public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "" + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Recieversmessage;
    private javax.swing.JLabel Recieversmessage1;
    private javax.swing.JLabel Recieversmessage2;
    private javax.swing.JLabel Recieversmessage3;
    private javax.swing.JButton backbutton;
    private netbeanscomponents.Donationlistlistcorpbackground donationlistlistcorpbackground1;
    private javax.swing.JPanel item1;
    private javax.swing.JPanel item2;
    private javax.swing.JPanel item3;
    private javax.swing.JPanel item4;
    private javax.swing.JLabel itemcategory;
    private javax.swing.JLabel itemcategory1;
    private javax.swing.JLabel itemcategory2;
    private javax.swing.JLabel itemcategory3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton logobutton;
    private javax.swing.JMenuItem logoutmenu;
    private javax.swing.JButton messagebutton;
    private javax.swing.JButton profilebutton;
    private javax.swing.JMenuItem profilemenu;
    private javax.swing.JLabel recieveraddress;
    private javax.swing.JLabel recieveraddress1;
    private javax.swing.JLabel recieveraddress2;
    private javax.swing.JLabel recieveraddress3;
    private javax.swing.JPanel wishlistlist;
    // End of variables declaration//GEN-END:variables
}
